version: '2'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keystone

  keystone:
    build: .
    hostname: sentinel.example.com
    ports:
      - "35357:35357"
      - "5000:5000"

  rabbit:
    image: rabbitmq:3-alpine
