version: '2'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keystone

  keystone:
    build: .
    ports:
      - "35357:35357"
      - "5000:5000"
    extra_hosts:
      - "sentinel.example.com:127.0.0.1"

  rabbit:
    image: rabbitmq:3-alpine
